### ISSUE TITLE
Intersection.intersectBezier2Bezier2 seems to be broken

### ISSUE THREAD

**Issue by smalljam** [thelonious/js-intersections#1]
intersect_bezier2_bezier2.svg example doesn't work

I've try to debug it, but the point is – I can't find sources for Path.prototype extending, it's hard to debug minified 2D.js, even after beautifying :)

Maybe you plan to outsource 2D library? Or it's already somewhere?

Your work is amazing, thank you for that.

**Comment by thelonious** [comment]
Hey smalljam,

I keep meaning to reply to this and then get distracted with work. I do have separate code for the 2D lib. I'll try to push that to a new project. I really created it to make it easier to test the intersections interactively, so it's pretty rough, but, then again, so is most of the SVG code I've been pushing to Github.

Thanks for you kind words.

-Kevin

**Comment by smalljam** [comment]
sounds cool, can't wait to see new 2d

Anton

**Comment by thelonious** [comment]
Hey Anton,

OK, the code is finally up. Apologies for the delay. It took a while to locate this old code. You can find the project here:

https://github.com/thelonious/svg-2d

I'm sure I'll be changing the repo name eventually and culling out some of the code. There's a fair amount of overlap of this code with other projects (including the intersection code). I have to decide if it's better to have one big "lib"-type project or separate ones like I have now.

Let me know how this works for you.

Thanks!

-Kevin
